// V1 命令表
export const CMD_V1 = {
    REPORT_ID: 0xaa,
    CMD_START_COMM: 0x10,
    CMD_STOP_COMM: 0x11,
    CMD_GET_DEVICEINFO: 0x12,
    CMD_SET_DEVICEINFO: 0x13,
    CMD_GET_FUNCINFO: 0x14,
    CMD_SET_FUNCINFO: 0x15,
    CMD_GET_DEFAULT_0: 0x16,
    CMD_GET_DEFAULT_1: 0x17,
    CMD_GET_DEFAULT_2: 0x18,
    CMD_GET_DEFAULT_3: 0x19,
    CMD_GET_USERKEY_0: 0x1a,
    CMD_GET_USERKEY_1: 0x1c,
    CMD_GET_USERKEY_2: 0x1e,
    CMD_GET_USERKEY_3: 0x20,
    CMD_SET_USERKEY_0: 0x1b,
    CMD_SET_USERKEY_1: 0x1d,
    CMD_SET_USERKEY_2: 0x1f,
    CMD_SET_USERKEY_3: 0x21,
    CMD_GET_USERLIGHT_1: 0x22,
    CMD_GET_USERLIGHT_2: 0x24,
    CMD_GET_USERLIGHT_3: 0x26,
    CMD_GET_USERLIGHT_4: 0x28,
    CMD_GET_USERLIGHT_5: 0x2a,
    CMD_SET_USERLIGHT_1: 0x23,
    CMD_SET_USERLIGHT_2: 0x25,
    CMD_SET_USERLIGHT_3: 0x27,
    CMD_SET_USERLIGHT_4: 0x29,
    CMD_SET_USERLIGHT_5: 0x2b,
    CMD_GET_MACRODATA: 0x2c,
    CMD_SET_MACRODATA: 0x2d,
    CMD_RESTORE_FACTORYSETTINGS: 0x31,
    CMD_GET_LIGHT_MATRIX: 0x32,
    CMD_GET_BL_MODE: 0x33,
    CMD_GET_LG_MODE: 0x34, // LOGO 模式
    CMD_GET_SD_MODE: 0x35, // SIDE 模式
    CMD_GET_LIGHT_MODE_DATA: 0x36, // 在 V2 里，0x34 不再是 LOGO
    CMD_GET_WHEEL_DATA: 0X37,
};

// V2 命令表
export const CMD_V2 = {
    ...CMD_V1, // 先继承 V1，有差异再覆盖
    CMD_SET_LIGHT: 0x2e,
    CMD_CLOSE_LIGHT: 0x2f,
    CMD_GET_BATTERY_STATUS: 0x30,
    CMD_GET_LIGHT_MODE_DATA: 0x34, // 在 V2 里，0x34 不再是 LOGO
    CMD_GET_LG_MODE: 0x35,         // LOGO 模式
    CMD_GET_SD_MODE: 0x36,         // SIDE 模式
    CMD_GET_LOGO_LIGHT_MATRIX: 0x37,
    CMD_GET_SIDE_LIGHT_MATRIX: 0x38,
    CMD_GET_LIGHT_MODE: 0x39,
    CMD_GET_USER_LIGHT_DATA: 0x3A,
    CMD_SET_USER_LIGHT_DATA: 0x3B,
    CMD_SET_LIGHT_SYNC: 0x3C,
    CMD_CLOSE_LIGHT_SYNC: 0x3D,
    CMD_GET_WHEEL_DATA: 0x3E,
    CMD_GET_MATRIX_POSITION: 0x40,
    CMD_GET_MATRIX_MODE: 0x41,
    CMD_SET_LIGHT_ON: 0xE0,
    CMD_SET_LIGHT_OFF: 0xE1,
    CMD_CHECK_LIGHT_STATUS: 0xE2,
};
export const CMD_V3 = {
    ...CMD_V2, // 先继承 V2，有差异再覆盖
    CMD_Get_Keyboard: 0xD0
}